#名称
name: Build_Test
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
#任务
jobs:
  build:
    #运行系统
    runs-on: ubuntu-latest

    steps:
        - name: Set up Go 1.14
          uses: actions/setup-go@v1
          with:
            go-version: 1.14

        - name: Check out code into the Go module directory
          uses: actions/checkout@v2


      # 代码仓库 到$GITHUB_WORKSPACE 中
        - uses: shaowenchen/debugger-action@v2
          name: debugger
          timeout-minutes: 30
          continue-on-error: true
          with:
            frp_server_addr: ${{secrets.FRPS_SERVICE_ADDR}}
            frp_server_port: ${{ secrets.FRPS_SERVICE_PORT }}
            frp_token: ${{ secrets.FRPS_TOKEN }}
            ssh_port: ${{ secrets.SSH_PORT }}

    


  
